// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asmsxfqmecqaorjjcpne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbXN4ZnFtZWNxYW9yampjcG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTc3NTMsImV4cCI6MjA2Nzg3Mzc1M30.Teau9rb1jl4AzRoW59nnNAFKeDHdreeZSIcEN7YbkmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});